#pragma config(Sensor, S3,     IRDistance1,    sensorSONAR_Inch)
#pragma config(Motor,  motorB,          left,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
IR Seeker Modes
0 - modeEV3IR_Proximity
1 - modeEV3IR_Seeker
2 - modeEV3IR_Remote
3 - modeEV3IR_Remote_Advanced
5 - modeEV3IR_Calibration
*/

task main()
{
	// Distance to maintain to the target.
  // This a percentage value of 0-100 and is not an actual distance
  // The value returns depends heavily on the type of material you are
  // measuring the distance to.  For example, cloth will absorb a lot of
  // the IR light and give a very high reading (big distance).
  // A while wall will reflect much more light, resulting in a lower
  // reading for the same distance.
	int distanceToMaintain = 90;

	int currentDistance = 0;

	while(true)
	{

		currentDistance = SensorValue[IRDistance1];

		displayCenteredBigTextLine(4, "Dist: %d", currentDistance);


		if ((distanceToMaintain - currentDistance) < 1)
		{
			motor[left] = -30;
			motor[right] = -30;
		}

		else if ((distanceToMaintain - currentDistance) >0)
		{
			motor[left] = 0;
			motor[right] = 0;
		}//end else if

		sleep(50);
	}//end while
}
