#pragma config(Sensor, S1,lightSensor,sensorLightActive)
//Code automatically generated by 'ROBOTC' configuration wizard

task main()
{
	int threshold = 30; //enter your threshold here

	//WHILE THE LIGHT SENSOR IS > THAN THE THRESHOLD MOVE FORWRD 50
	while(SensorValue(lightSensor) > threshold)
	{
		motor[motorC] = 50;
		motor[motorB] = 50;

	}//end while

	while(SensorValue(lightSensor) < threshold)
	{
		motor[motorC] = 0;
		motor[motorB] = 0;
	}//end while

	motor[motorB] = -50;
	motor[motorC] = -50;
	wait1Msec(1000);

}//end main()
