#pragma config(Sensor, S3,     soundSensor,    sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*The following program will be used to detect sound. Lab 5 part 7*/
//implementing sound. go to view mode and view sound db
//make low and high sounds to test the mic
//find the threshold. min + max / 2
void forward(int power)
{
  motor[motorC]=power;
  motor[motorB]=power;
  wait1Msec(10000);

}//end forward

#define MIN 10
#define MAX 51
task main()
{
  //int thresholdSound = MIN + MAX / 2;
  int power = SensorValue(soundSensor);
  forward(power);

}//end main()
